language: node_js
node_js:
  - "0.12"

cache:
  directories:
    - node_modules

before_install:
  - npm install --global npm
  - npm --version
  - npm install --global gulp-cli
  - gulp --version

install:
  - npm install

script:
  - gulp lint
  - gulp test

